[keyboard]
[[keyboard.bindings]]
chars = "\u0017"
key = "Back"
mods = "Control"

[font]
size = 10.0
normal = { family = "Cousine", style = "Regular" }

# [font]
# size = 10.0
# normal = { family = "Noto Sans Mono", style = "Regular", fallback = "Symbols Nerd Font Mono" }

